### ISSUE TITLE
too many issues 

### ISSUE THREAD

**Issue by josephlandau** [katywarr/strengthening-dnns#6]
I keep having issues with the tensorflow code. is this written in tensorflow 1?

**Comment by katywarr** [comment]
Really sorry you are having issues.
Yes, at the time of writing only TF1 was available. 
If you use the getting started instructions, tthat will set up your environment with all the correct dependencies and should solve the issues.

**Comment by josephlandau** [comment]
The environmental setup for what you are talking about will preclude me
from being able to use plaidml since i have an amd gpu

ValueError: Unable to import backend : plaidml.keras.backend

**Comment by katywarr** [comment]
Hi again

It's difficult to work out what is going on, as I have no details of when the error is being thrown, but it does sound like an installation problem. I don't know what environment/installation steps you have. It may also be that a specific library does not work with PlaidML - again difficult to tell with the information given.

The code in this repository has been deliberately written as demonstration/explanatory code that can be run on a CPU so people don't require a GPU to run it. It will therefore run without your GPU.

If you need to use the GPU, I suggest you re-check the installation instructions for https://plaidml.github.io/plaidml/docs/install.html. I am very happy to receive pull requests if you would like the installation instructions updated to work with PlaidML, but I need to retain the core code so that it remains aligned with what is printed in the book and still runs with CPUs.

Thanks!

**Comment by katywarr** [comment]
Closing this issue as not supported - as mentioned above, the code is for demo/learning using CPU.  
Happy to receive pull request to extend the functionality however to run with PlaidML (if it does not deviate too far from the code in the book). Thanks
